version: "3.1"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    container_name: backend
    depends_on: 
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: pratik
      DB_PASSWORD: pratik1234
      DB_NAME: testdb
      DB_PORT: 5432
      ALLOWED_ORIGINS: '*'
    networks:
      - mynetwork  
  # Redis Service   
  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    restart: always
    container_name: database
    environment:
      POSTGRES_PASSWORD: pratik1234
      POSTGRES_USER: pratik
      POSTGRES_DB: testdb
    networks:
      - mynetwork  

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    container_name: frontend
    environment:
      REACT_APP_SERVER_URL: http://localhost:8080/employees
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
