name: Terraform Azure Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  pull_request:
    paths:
      - 'terraform/**'

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBCRIPTION_ID: ${{ secret.ARM_SUBCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secret.ARM_TENANT_ID }}
  TF_WORKING_DIR: './terraform'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.4

    - name: Initialize Terraform
      run: terraform -chdir=${{ env.TF_WORKING_DIR }} init

    - name: Terraform Plan
      run: terraform -chdir=${{ env.TF_WORKING_DIR }} plan -out=tfplan

    - name: Terraform Apply
      if: ${{ github.ref == 'refs/heads/main'}}
      run: terraform -chdir=${{ env.TF_WORKING_DIR }} apply -input=false tfplan
